### ISSUE TITLE
Issue reported byU:.Aztharo | Artur(216970882923364352)

### ISSUE THREAD

**Issue by DiscordBotMarv** [MemphisCornelius/MarvBot#3]
Tot
also, timo wird in AFK channel  gemoved. AFK Channel wird in Counter strike umgenannt und nach 3 sec wieder in AFK channel umbenannt
okay keijn bock

**Comment by MemphisCornelius** [comment]
Der Bug sollte mit dem nächsten commit gefixed sein.
